# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SleepTimerGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CountdownTimer(object):
    def setupUi(self, CountdownTimer):
        CountdownTimer.setObjectName("SleepTimerGUI")
        CountdownTimer.setFixedSize(430, 550)
        CountdownTimer.setStyleSheet("")
        CountdownTimer.setIconSize(QtCore.QSize(30, 34))
        self.centralwidget = QtWidgets.QWidget(CountdownTimer)
        self.centralwidget.setStyleSheet("QWidget{\n"
"background-color: rgb(46, 46, 46);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.CircularProgressBarBase = QtWidgets.QFrame(self.centralwidget)
        self.CircularProgressBarBase.setGeometry(QtCore.QRect(55, 45, 320, 320))
        self.CircularProgressBarBase.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CircularProgressBarBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CircularProgressBarBase.setObjectName("CircularProgressBarBase")
        self.CircularProgress = QtWidgets.QFrame(self.CircularProgressBarBase)
        self.CircularProgress.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.CircularProgress.setStyleSheet("QFrame{\n"
"    border-radius: 150px;\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:1.0 rgba(57, 192, 237, 255), stop:2.0 rgba(255, 255, 255, 0));\n"
"}")
        self.CircularProgress.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CircularProgress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CircularProgress.setObjectName("CircularProgress")
        self.CircularBg = QtWidgets.QFrame(self.CircularProgressBarBase)
        self.CircularBg.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.CircularBg.setStyleSheet("QFrame{\n"
"    border-radius: 150px;\n"
"    background-color: rgb(189, 189, 189);\n"
"}")
        self.CircularBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CircularBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CircularBg.setObjectName("CircularBg")
        self.container = QtWidgets.QFrame(self.CircularProgressBarBase)
        self.container.setGeometry(QtCore.QRect(20, 20, 280, 280))
        self.container.setStyleSheet("QFrame{\n"
"    border-radius: 140px;\n"
"    background-color: rgb(46, 46, 46);\n"
"}")
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.layoutWidget = QtWidgets.QWidget(self.container)
        self.layoutWidget.setGeometry(QtCore.QRect(35, 60, 211, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Total_Time_Label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.Total_Time_Label.setFont(font)
        self.Total_Time_Label.setStyleSheet("QLabel{\n"
"    color: rgb(255 , 255, 255);\n"
"    background-color: none;\n"
"}")
        self.Total_Time_Label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Total_Time_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Total_Time_Label.setObjectName("Total_Time_Label")
        self.gridLayout.addWidget(self.Total_Time_Label, 0, 0, 1, 1)
        self.Time_Label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.Time_Label.setFont(font)
        self.Time_Label.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: none;\n"
"}")
        self.Time_Label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Time_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Time_Label.setObjectName("Time_Label")
        self.gridLayout.addWidget(self.Time_Label, 1, 0, 1, 1)
        self.Time_Percent = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        self.Time_Percent.setFont(font)
        self.Time_Percent.setStyleSheet("QLabel{\n"
"    color: rgb(57, 192, 237);\n"
"    background-color: none;\n"
"}")
        self.Time_Percent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Time_Percent.setAlignment(QtCore.Qt.AlignCenter)
        self.Time_Percent.setObjectName("Time_Percent")
        self.gridLayout.addWidget(self.Time_Percent, 2, 0, 1, 1)
        self.CircularBg.raise_()
        self.CircularProgress.raise_()
        self.container.raise_()
        self.StopButtonBase = QtWidgets.QFrame(self.centralwidget)
        self.StopButtonBase.setGeometry(QtCore.QRect(115, 430, 70, 70))
        self.StopButtonBase.setStyleSheet("QFrame{\n"
"    border: 4px solid rgb(57, 192, 237);\n"
"    border-radius: 35px;\n"
"    background-color: rgb(80, 80, 80);\n"
"}")
        self.StopButtonBase.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.StopButtonBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.StopButtonBase.setObjectName("StopButtonBase")
        self.Stop_Button_Label = QtWidgets.QLabel(self.StopButtonBase)
        self.Stop_Button_Label.setGeometry(QtCore.QRect(15, 16, 38, 39))
        self.Stop_Button_Label.setStyleSheet("QLabel{\n"
"border-color: none;\n"
"}")
        self.Stop_Button_Label.setLineWidth(0)
        self.Stop_Button_Label.setText("")
        self.Stop_Button_Label.setPixmap(QtGui.QPixmap("img/stop.png"))
        self.Stop_Button_Label.setObjectName("Stop_Button_Label")
        self.Stop_Button = QtWidgets.QPushButton(self.StopButtonBase)
        self.Stop_Button.setGeometry(QtCore.QRect(0, 0, 70, 70))
        self.Stop_Button.setStyleSheet("QPushButton{\n"
"    border-radius: 35px;\n"
"    background-color: none;\n"
"}")
        self.Stop_Button.setText("")
        self.Stop_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Stop_Button.setObjectName("Stop_Button")
        self.PauseButtonBase = QtWidgets.QFrame(self.centralwidget)
        self.PauseButtonBase.setGeometry(QtCore.QRect(245, 430, 70, 70))
        self.PauseButtonBase.setStyleSheet("QFrame{\n"
"    border: 4px solid rgb(57, 192, 237);\n"
"    border-radius: 35px;\n"
"    background-color: rgb(80, 80, 80);\n"
"}")
        self.PauseButtonBase.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PauseButtonBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PauseButtonBase.setObjectName("PauseButtonBase")
        self.Pause_Button_Label = QtWidgets.QLabel(self.PauseButtonBase)
        self.Pause_Button_Label.setGeometry(QtCore.QRect(16, 16, 38, 39))
        self.Pause_Button_Label.setStyleSheet("QLabel{\n"
"border-color: none;\n"
"}")
        self.Pause_Button_Label.setLineWidth(0)
        self.Pause_Button_Label.setText("")
        self.Pause_Button_Label.setPixmap(QtGui.QPixmap("img/pause.png"))
        self.Pause_Button_Label.setScaledContents(False)
        self.Pause_Button_Label.setObjectName("Pause_Button_Label")
        self.Pause_Button = QtWidgets.QPushButton(self.PauseButtonBase)
        self.Pause_Button.setGeometry(QtCore.QRect(0, 0, 70, 70))
        self.Pause_Button.setStyleSheet("QPushButton{\n"
"    border-radius: 35px;\n"
"    background-color: none;\n"
"}")
        self.Pause_Button.setText("")
        self.Pause_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Pause_Button.setObjectName("Pause_Button")
        CountdownTimer.setCentralWidget(self.centralwidget)

        self.retranslateUi(CountdownTimer)
        QtCore.QMetaObject.connectSlotsByName(CountdownTimer)

    def retranslateUi(self, CountdownTimer):
        _translate = QtCore.QCoreApplication.translate
        CountdownTimer.setWindowTitle(_translate("SleepTimerGUI", "MainWindow"))
        self.Total_Time_Label.setText(_translate("SleepTimerGUI", "<html><head/><body><p><span style=\" font-weight:600; color:#39c0ed;\">TOTAL:</span> 00 : 00 : 00</p></body></html>"))
        self.Time_Label.setText(_translate("SleepTimerGUI", "<strong>00 : 00 : 00</strong>"))
        self.Time_Percent.setText(_translate("SleepTimerGUI", "<p><span style=\" font-size:25pt;\">0</span><span style=\" font-size:19pt; vertical-align:super;\">%</span></p>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CountdownTimer = QtWidgets.QMainWindow()
    ui = Ui_CountdownTimer()
    ui.setupUi(CountdownTimer)
    CountdownTimer.show()
    sys.exit(app.exec_())
