# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditTimerScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditTimerScreen(object):
    def setupUi(self, EditTimerScreen):
        EditTimerScreen.setObjectName("EditTimerScreen")
        EditTimerScreen.setFixedSize(430, 550)
        EditTimerScreen.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(EditTimerScreen)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(46, 46, 46);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.Hours_Container = QtWidgets.QFrame(self.centralwidget)
        self.Hours_Container.setGeometry(QtCore.QRect(55, 40, 320, 100))
        self.Hours_Container.setStyleSheet("QFrame{\n"
"    \n"
"}")
        self.Hours_Container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Hours_Container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Hours_Container.setObjectName("Hours_Container")
        self.Hours_Label = QtWidgets.QLabel(self.Hours_Container)
        self.Hours_Label.setGeometry(QtCore.QRect(15, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Hours_Label.setFont(font)
        self.Hours_Label.setStyleSheet("QLabel{\n"
"    border: none;\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.Hours_Label.setObjectName("Hours_Label")
        self.Hours_spinBox = QtWidgets.QSpinBox(self.Hours_Container)
        self.Hours_spinBox.setGeometry(QtCore.QRect(164, 35, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.Hours_spinBox.setFont(font)
        self.Hours_spinBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Hours_spinBox.setStyleSheet("QSpinBox{\n"
"    border: 2px solid rgb(57, 192, 237);\n"
"    border-top-left-radius: 8px;\n"
"    border-bottom-left-radius: 8px;\n"
"    color: rgb(57, 192, 237);\n"
"    padding-left: 55px;\n"
"}")
        self.Hours_spinBox.setMaximum(24)
        self.Hours_spinBox.setObjectName("Hours_spinBox")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(40, 155, 350, 2))
        self.line.setStyleSheet("Line{\n"
"    border: 2px solid rgb(57, 192, 237);\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Minutes_Container = QtWidgets.QFrame(self.centralwidget)
        self.Minutes_Container.setGeometry(QtCore.QRect(55, 180, 320, 100))
        self.Minutes_Container.setStyleSheet("QFrame{\n"
"    \n"
"}")
        self.Minutes_Container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Minutes_Container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Minutes_Container.setObjectName("Minutes_Container")
        self.Minutes_Label = QtWidgets.QLabel(self.Minutes_Container)
        self.Minutes_Label.setGeometry(QtCore.QRect(15, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Minutes_Label.setFont(font)
        self.Minutes_Label.setStyleSheet("QLabel{\n"
"    border: none;\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.Minutes_Label.setObjectName("Minutes_Label")
        self.Minutes_spinBox = QtWidgets.QSpinBox(self.Minutes_Container)
        self.Minutes_spinBox.setGeometry(QtCore.QRect(164, 35, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.Minutes_spinBox.setFont(font)
        self.Minutes_spinBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Minutes_spinBox.setStyleSheet("QSpinBox{\n"
"    border: 2px solid rgb(57, 192, 237);\n"
"    border-top-left-radius: 8px;\n"
"    border-bottom-left-radius: 8px;\n"
"    color: rgb(57, 192, 237);\n"
"    padding-left: 55px;\n"
"}")
        self.Minutes_spinBox.setMaximum(60)
        self.Minutes_spinBox.setProperty("value", 30)
        self.Minutes_spinBox.setObjectName("Minutes_spinBox")
        self.Seconds_Container = QtWidgets.QFrame(self.centralwidget)
        self.Seconds_Container.setGeometry(QtCore.QRect(55, 320, 320, 100))
        self.Seconds_Container.setStyleSheet("QFrame{\n"
"    \n"
"}")
        self.Seconds_Container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Seconds_Container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Seconds_Container.setObjectName("Seconds_Container")
        self.Seconds_Label = QtWidgets.QLabel(self.Seconds_Container)
        self.Seconds_Label.setGeometry(QtCore.QRect(15, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Seconds_Label.setFont(font)
        self.Seconds_Label.setStyleSheet("QLabel{\n"
"    border: none;\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.Seconds_Label.setObjectName("Seconds_Label")
        self.Seconds_spinBox = QtWidgets.QSpinBox(self.Seconds_Container)
        self.Seconds_spinBox.setGeometry(QtCore.QRect(164, 35, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.Seconds_spinBox.setFont(font)
        self.Seconds_spinBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Seconds_spinBox.setStyleSheet("QSpinBox{\n"
"    border: 2px solid rgb(57, 192, 237);\n"
"    border-top-left-radius: 8px;\n"
"    border-bottom-left-radius: 8px;\n"
"    color: rgb(57, 192, 237);\n"
"    padding-left: 55px;\n"
"}")
        self.Seconds_spinBox.setMaximum(60)
        self.Seconds_spinBox.setObjectName("Seconds_spinBox")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(40, 295, 350, 2))
        self.line_2.setStyleSheet("Line{\n"
"    border: 2px solid rgb(57, 192, 237);\n"
"}")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.ValidButtonBase = QtWidgets.QFrame(self.centralwidget)
        self.ValidButtonBase.setGeometry(QtCore.QRect(180, 450, 70, 70))
        self.ValidButtonBase.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ValidButtonBase.setStyleSheet("QFrame{\n"
"    border: 4px solid rgb(57, 192, 237);\n"
"    border-radius: 35px;\n"
"    background-color: rgb(80, 80, 80);\n"
"}")
        self.ValidButtonBase.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ValidButtonBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ValidButtonBase.setObjectName("ValidButtonBase")
        self.Valid_Button_Label = QtWidgets.QLabel(self.ValidButtonBase)
        self.Valid_Button_Label.setGeometry(QtCore.QRect(14, 19, 43, 33))
        self.Valid_Button_Label.setStyleSheet("QLabel{\n"
"border-color: none;\n"
"}")
        self.Valid_Button_Label.setLineWidth(0)
        self.Valid_Button_Label.setText("")
        self.Valid_Button_Label.setPixmap(QtGui.QPixmap("img/check.png"))
        self.Valid_Button_Label.setObjectName("Valid_Button_Label")
        self.Valid_Button = QtWidgets.QPushButton(self.ValidButtonBase)
        self.Valid_Button.setGeometry(QtCore.QRect(0, 0, 70, 70))
        self.Valid_Button.setStyleSheet("QPushButton{\n"
                                        "    border-radius: 35px;\n"
                                        "    background-color: none;\n"
                                        "}")
        self.Valid_Button.setText("")
        self.Valid_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Valid_Button.setObjectName("Valid_Button")
        EditTimerScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(EditTimerScreen)
        QtCore.QMetaObject.connectSlotsByName(EditTimerScreen)

    def retranslateUi(self, EditTimerScreen):
        _translate = QtCore.QCoreApplication.translate
        EditTimerScreen.setWindowTitle(_translate("EditTimerScreen", "EditTimerScreen"))
        self.Hours_Label.setText(_translate("EditTimerScreen", "Hours:"))
        self.Minutes_Label.setText(_translate("EditTimerScreen", "Minutes"))
        self.Seconds_Label.setText(_translate("EditTimerScreen", "Seconds"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditTimerScreen = QtWidgets.QMainWindow()
    ui = Ui_EditTimerScreen()
    ui.setupUi(EditTimerScreen)
    EditTimerScreen.show()
    sys.exit(app.exec_())
