# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomeScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeScreen(object):
    def setupUi(self, HomeScreen):
        HomeScreen.setObjectName("MainWindow")
        HomeScreen.setFixedSize(430, 550)
        self.centralwidget = QtWidgets.QWidget(HomeScreen)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(46, 46, 46);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.Select_Time_Countainer = QtWidgets.QFrame(self.centralwidget)
        self.Select_Time_Countainer.setGeometry(QtCore.QRect(55, 45, 320, 320))
        self.Select_Time_Countainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Select_Time_Countainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Select_Time_Countainer.setObjectName("Select_Time_Countainer")
        self.Select_Time_Label = QtWidgets.QLabel(self.Select_Time_Countainer)
        self.Select_Time_Label.setGeometry(QtCore.QRect(0, 100, 311, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        self.Select_Time_Label.setFont(font)
        self.Select_Time_Label.setStyleSheet("QLabel{\n"
"    color: rgb(57, 192, 237);\n"
"}")
        self.Select_Time_Label.setObjectName("Select_Time_Label")
        self.Select_Time_Button = QtWidgets.QPushButton(self.Select_Time_Countainer)
        self.Select_Time_Button.setGeometry(QtCore.QRect(0, 100, 311, 81))
        self.Select_Time_Button.setStyleSheet("QPushButton{\n"
"    border-radius: 35px;\n"
"    background-color: none;\n"
"}")
        self.Select_Time_Button.setText("")
        self.Select_Time_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Select_Time_Button.setObjectName("Select_Time_Button")
        self.StartButtonBase = QtWidgets.QFrame(self.centralwidget)
        self.StartButtonBase.setGeometry(QtCore.QRect(180, 430, 70, 70))
        self.StartButtonBase.setStyleSheet("QFrame{\n"
"    border: 4px solid rgb(57, 192, 237);\n"
"    border-radius: 35px;\n"
"    background-color: rgb(80, 80, 80);\n"
"}")
        self.StartButtonBase.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.StartButtonBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.StartButtonBase.setObjectName("StartButtonBase")
        self.Start_Button_Label = QtWidgets.QLabel(self.StartButtonBase)
        self.Start_Button_Label.setGeometry(QtCore.QRect(18, 14, 38, 42))
        self.Start_Button_Label.setStyleSheet("QLabel{\n"
"border-color: none;\n"
"}")
        self.Start_Button_Label.setLineWidth(0)
        self.Start_Button_Label.setText("")
        self.Start_Button_Label.setPixmap(QtGui.QPixmap("img/play.png"))
        self.Start_Button_Label.setObjectName("Start_Button_Label")
        self.Start_Button = QtWidgets.QPushButton(self.StartButtonBase)
        self.Start_Button.setGeometry(QtCore.QRect(0, 0, 70, 70))
        self.Start_Button.setStyleSheet("QPushButton{\n"
"    border-radius: 35px;\n"
"    background-color: none;\n"
"}")
        self.Start_Button.setText("")
        self.Start_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Start_Button.setObjectName("Start_Button")
        HomeScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(HomeScreen)
        QtCore.QMetaObject.connectSlotsByName(HomeScreen)

    def retranslateUi(self, HomeScreen):
        _translate = QtCore.QCoreApplication.translate
        HomeScreen.setWindowTitle(_translate("HomeScreen", "HomeScreen"))
        self.Select_Time_Label.setText(_translate("HomeScreen", "<strong>00 : 30 : 00</strong>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomeScreen = QtWidgets.QMainWindow()
    ui = Ui_HomeScreen()
    ui.setupUi(HomeScreen)
    HomeScreen.show()
    sys.exit(app.exec_())
